config/routes.rb
Rails.application.routes.draw do

  get 'profiles/index'
  get 'profiles/show'
  get 'profiles/edit'
  get 'profiles/update'
  get 'profiles/show'
  resources :listings, only: :index
  resources :deals, only: :index

  post '/accept/:id', to: 'listings#accept', as: 'accept'
  post '/reject/:id', to: 'listings#reject', as: 'reject'

  devise_for :users
  #   devise_scope :user do
  #   authenticated :user do
  #     root 'items#index', as: :authenticated_root
  #   end

  #   unauthenticated do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  #   end
  # end

  root 'items#index'



  devise_for :owners
# def root
#   if owner_signed_in?
#     redirect_to 'listings#index'
#   else
#     redirect_to 'items#index'
#   end
# end
#   devise_scope :owner do
#   authenticated :owner do
#     root 'listings#index', as: :authenticated_root
#   end
#     unauthenticated do
#     root to: , as: :unauthenticated_root
#   end
# end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # browse all items
  # /items => items#index(owner_id=nil)

  # POST /items => items#create
  resources :items, only: [:index, :show, :create, :destroy, :new, :edit, :update] do
    resources :deals, only: [:create, :index, :show, :new]
  end


  # view an item
  # /items/42 => items#show

  # browse all items of an owner
  # /owners/1/items => items#index(owner_id=1)
  resources :owners do
    resources :items, only: :index
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :item
  belongs_to :user

  def set
    self.end_date = Date.today + duration
    self.status = "ongoing"
  end

  def self.ongoing
    deals = Deal.where(status: "ongoing")
    deals.each do |deal|
      if deal.end_date < Date.today
        deal.status = "finished"
        deal.save
      end
    end
  end

def self.show
    deals = Deal.where(status: "ongoing")
    items_to_change = []
    deals.each do |deal|
      items_to_change << Item.find(deal.item_id)
    end

    items_to_change.each do |item|
      item.list = false
      item.save
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates :description, presence: true
  validates :name, presence: true
  validates :price, presence: true
  belongs_to :owner
  has_many :deals, dependent: :destroy
  mount_uploader :photos, PhotoUploader

  include PgSearch
  # Movie.search_by_title_and_syllabus(query)
  pg_search_scope :search_by_name_and_description,
    against: {
      name: 'A',
      description: 'B'
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :items
  has_many :deals, through: :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :deals
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_owner!


  include Pundit


  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private
  def skip_pundit?
        devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticate_user!

  def index
    @deals = current_user.deals
    # @deals = policy_scope(Deal)
    # skip policy scope
    skip_policy_scope
  end

  def new
    @item = Item.find(params[:id])
    authorize @deal
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(deal_params)
    @deal.user = current_user
    @deal.item = Item.find(params[:item_id])
    @deal.start_date = Date.today
    @deal.status = "pending"
    authorize @deal
    @deal.save
    redirect_to root_path
  end

  private

  def deal_params
    params.require(:deal).permit(:duration)
  end

  def set_deal
    @deal = Deal.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_owner!, except: [:index, :show]

  def index
    Deal.ongoing
    Deal.show

    if params[:query].present?
      @items = Item.search_by_name_and_description(params[:query])
    else
      @items = Item.all
    end

    @list_items = @items.where(list: true)

    @markers = @items.map do |item|
      {
        lat: item.owner.latitude,
        lng: item.owner.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { item: item })

      }
    end
    # raise
  end

  def show
    @items = Item.find(params[:id])
    @deal = Deal.new
  end

  def new
    @item = Item.new
    # @item.save
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.owner = current_owner
    authorize @item
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was created."}
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @item
  end

  def update
    authorize @item

    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    authorize @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was destroyed."}
      format.json {head :no_content}
    end
  end

  private

  def pundit_user
    current_owner
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :description, :photos)
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_owner!
  # before_action :set_owner, only: [:show, :update, :destroy, :index]

  def index
    Deal.ongoing
    @items = policy_scope(Item)
    @pending_deals = current_owner.deals.where(status: 'pending')
    @current_deals = current_owner.deals.where(status: 'ongoing')
    @finished_deals = current_owner.deals.where(status: 'finished')
  end

  def accept
   @deal = Deal.find(params[:id])
   @deal.set
   @deal.save!
  end

  def reject
   @deal = Deal.find(params[:id])
   @deal.status = "rejected"
   @deal.list = true
   @deal.save!
  end

  private

  def set_owner
    @owner = Owner.find(params[:id])
  end

  def pundit_user
    current_owner
  end
end
# first add migration to edit status to string
# in list controller#index put @deals = deals.where status == "pending"
#

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :authenticate_owner!

  def show
    @owner = current_owner
    @items = policy_scope(Item)
    @pending_deals = current_owner.deals.where(status: 'pending')
    @current_deals = current_owner.deals.where(status: 'ongoing')
    @finished_deals = current_owner.deals.where(status: 'finished')
  end
  # def profile
  #   @owner.address = current_address
  #   @owner.city = current_city
  #   @owner.country = current_country
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deals/index.html.erb
<div class="container-main" style="text-align:center;">
<div class="container-form-address">
  <h2 style="margin:50px 0px;">Hello Pontus</h2>
  <p><%= current_user.address %></p>

  </div>
  </div>


<div class="container-main" style="text-align:center;">
    <h3 class="text-slim">My Deals</h3>

<h2 class="text-slim">Waiting to hear from owner</h2>
  <div class="listings-flex">
  <% @deals.each do |deal| %>
    <% if deal.status == 'pending' %>
        <div class="main-group">
              <p><%= deal.item.name %></p>
              <p><%= deal.item.price %></p>
              <p><%= deal.duration %></p>
        </div>
    <% end %>
  <% end %>
  </div>







<h2>Your Current Deals</h2>

  <div class="listings-flex">
  <% @deals.each do |deal| %>
    <% if deal.status == 'ongoing' %>
        <div class="main-group">
              <p><%= deal.item.name %></p>
              <p><%= deal.item.price %></p>
              <p><%= deal.duration %></p>
        </div>
    <% end %>
  <% end %>
  </div>
  </div>
  </div>

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :price %>
  </div>

    <div class="form-inputs">
    <%= f.input :description %>
  </div>
  <div class="form-photo">
  <%= f.input :photos %>

  </div>


  <div class="form-actions">
    <%= f.button :submit, :class => "button-small button-margin" %>
  </div>
<% end %>

app/views/items/_formRent.html.erb
<%= simple_form_for([@item, @deal]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :duration, collection: [1, 2, 3, 4, 5, 6, 7], prompt: "How long would you like to rent?" %>
  </div>


  <div class="form-actions ">
    <%= f.button :submit, :class => "button-large-color" %>
  </div>
<% end %>

app/views/items/_infowindow.html.erb
<h3><%= item.name %></h3>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<head>
    <title>Edit Items</title>
</head>
<h1>Your can edit your item here.</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @item do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <h4>Change item image.</h4>
      <span class="picture">
        <%= f.file_field :photos, accept: 'image/jpeg,image/gif,image/png' %>
      </span>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>



  </div>
</div>

app/views/items/index.html.erb
<head>
    <title>Pierce Gears</title>
    <meta name="description" content="A fun platform to rent sporting and camping gears from people near you, so you can travel light, save time and money.">
</head>
<div class="section_one">
<div class="banner-main" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1459378560864-f0b73495599c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80);">

 <h2>FIND THE BEST GEAR FOR YOUR NEXT <br><span class="banner-text-style"> BIG ADVENTURE</span></h2>
 <a class="button-large scroll-event-button" href="">FIND GEAR</a>
 </div>

<div class="container-form">
<%= form_tag root_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control margin-title",
    placeholder: "Find a gear to rent"
  %>
<% end %>
</div>


<div class="section-two">
<div class="container-main">
<h2 class="text-center text-fat margin-title text-large">Top Picks</h2>
<div class="grid-main">
  <% @list_items.each do |item| %>
  <div class="card-mainpage">
    <%= cl_image_tag( item.photos,
      width: 270, height: 200) %>
      <div class="card-mainpage-text flexbox-card ">
    <%= link_to item.name.capitalize, item_path(item), :class => "text-card text-fat card-margin" %>
    <h3 class="text-card text-slim card-margin"><%= item.price %> $</h3>
    </div>
    </div>
    <% end %>
    </div>
   </div>
  </div>

  <div
    id="map"
    style="width: 400px;
    height: 400px; margin:50px auto; box-shadow: 0 0 15px rgba(0,0,0,0.2);"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

app/views/items/new.html.erb
<div class="container-form">
<h1 class="text-center text-fat margin-title">New Item</h1>

<%= render 'form', item: @item %>


<%= link_to 'Back', listings_path, :class => "button-small" %>

</div>

app/views/items/show.html.erb
<head>
 <title><%= @item.name %></title>
</head>
<div class="container-form">
 <div class="center-text flexbox margin-title box-shadow">
   <%= cl_image_tag(@item.photos, width:300, height:300, :class => "image-border-radius box-shadow") %>
   <div class="group-showpage-text margin-card">
     <h2 class="text-large"><%= @item.name.capitalize %></h2>
     <h3 class="text-small text-slim"><%= @item.description.capitalize %></h3>
       <p class="text-banner margin-title"><%= @item.price %>$</p>
       <%= link_to "Edit", edit_item_path, :class => "button-large-color"%>
   </div>
 </div>

 <div class="margin-title">
   <%= render 'formRent', item: @deal %>
 </div>
</div>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%#= stylesheet_pack_tag 'application', media: 'all' %>
      <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    </head>
    <body>
      <div class="navbar-main">
        <%= link_to image_tag("logo.png", :alt => "Image Description", width:140), root_path %>

        <div class="group-navbar">
          <div class="navbar-list">

              <% if user_signed_in? %>
              <ul>
                <li><%= link_to "Home", root_path %></li>
                <li><a class="scroll-event-menu" href="">Find Gear</a></li>
                <li><%= link_to "Profile", deals_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "button-small-red" %></li>
                <%= link_to image_tag("steven.png", :alt => "Image Description", :class => "avatar"), listings_path %>
                <li><p style="font-size:10px; opacity:0.5; margin-right:10px; font-weight:800;">USER</p></li>
                </ul>
              <% elsif owner_signed_in? %>
              <ul>
              <li><a style="display:none;" class="scroll-event-menu" href="">Find Gear</a></li>
              <li><%= link_to "Current Deals", listings_path %></li>
              <li><%= link_to "List New Gear", listings_path %></li>
              <li><%= link_to "Profile", owner_path(current_owner) %></li>
              <li><%= link_to "Log Out", destroy_owner_session_path, method: :delete, :class => "button-small-red" %></li>
              <%= link_to image_tag("profile.jpg", :alt => "Image Description", :class => "avatar"), listings_path %>
              <li><p style="font-size:10px; opacity:0.5; margin-right:10px; font-weight:800;">OWNER</p></li>
              </ul>
              <% else %>
              <ul>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Find Gear", items_path, :class => "scroll-event-menu" %></li>
                <li><%= link_to "Rent Gear", listings_path%></li>
                <li><%= link_to "Register", new_user_registration_path, :href => "#popup2" %></li>
                <li><a class="button-small " href="#popup1">Log In</a></li>
                </ul>
              <% end %>


            <div id="popup2" class="overlay text-center">
              <div class="popup">
                <h2 class="text-center">Register as</h2>
                <a class="close" href="#">&times;</a>
                <div class="content">
                  <a href="/users/sign_up">User</a>
                  <a href="/owners/sign_up">Owner</a>
                  </div>
                  </div>
                  </div>

            <div id="popup1" class="overlay text-center">
              <div class="popup">
                <h2 class="text-center">Sign in as</h2>
                <a class="close" href="#">&times;</a>
                <div class="content">
                  <a href="/users/sign_in">User</a>
                  <a href="/owners/sign_in">Owner</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= yield %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>

      <div class="footer-main">
        <div class="footer-text">
          <h2>PierceGear</h2>
          <ul>
            <li>
              <a href="">Home</a>
            </li>
            <li>
              <a href="">Find Gear</a>
            </li>
            <li>
              <a href="">Rent Gear</a>
            </li>
            <li>
              <a href="">Register</a>
            </li>
            <li>
              <a href="">Log In</a>
            </li>

          </ul>
          <p>© PierceGear International LTD.</p>
        </div>
      </div>


    </body>
  </html>

app/views/listings/index.html.erb
<head>
  <title>Owner's Dashboard</title>
</head>
<p id="notice"><%= notice %></p>


<div class="container-main">
  <div class="container-button" style="margin-top:50px;">
      <%= link_to 'New Item', new_item_path, class: "button-large-color";%>
    </div>
  <h2 class="center-text text-fat margin-title text-medium">Current Listings</h2>
    <% @items.each do |item| %>
    <div class="card-horizontal">
       <%= cl_image_tag item.photos, height: 100, width: 100, crop: :fill, :class => "card-horizontal-image" %>
       <div class="card-horizontal-text">
        <p><%= link_to item.name.capitalize, item_path(item) %></p>
          <p><%= item.price %>$ </p>
          </div>
          </div>
        <% end %>


        <h2 class="center-text text-fat margin-title text-medium">Your Current Deals</h2>
        <% @pending_deals.each do |deal| %>
        <div class="card-horizontal">
          <%= cl_image_tag deal.item.photos, height: 100, width: 100, :class => "card-horizontal-image" %>
        <div class="card-horizontal-text">
        <p style="font-weight:800;"><%= deal.item.name %></p>
        <p style="font-weight:800";><%= deal.duration %> days</p>
       <p style="font-weight:200;">Total: <%= deal.duration * deal.item.price %></p>
        <div class="group-this" style="flex-direction-column;">
       <%= button_to "ACCEPT",{ action: "accept", id: deal.id }, data: { confirm: "Are you sure?" }, :class => "button-accept" %>
        <%= button_to "REJECT", { action: "reject", id: deal.id }, data: { confirm: "Are you sure?" }, :class => "button-decline" %>
        </div>

       </div>
       </div>
        <% end %>


        <h2 class="center-text text-fat margin-title text-medium">Your Finished Deals</h2>
        <% @finished_deals.each do |deal| %>
        <div class="card-horizontal">
          <%= cl_image_tag deal.item.photos, height: 100, width: 100, :class => "card-horizontal-image" %>
        <div class="card-horizontal-text">
        <p style="font-weight:800;"><%= deal.item.name %></p>
        <p style="font-weight:800";>Finished on <%= deal.end_date%></p>
       <p style="font-weight:200;">Total: <%= deal.duration * deal.item.price %></p>

       </div>
       </div>
        <% end %>



        <div class="container-button">
          <%= link_to 'New Item', new_item_path, class: "button-large-color" %>
          </div>


<!--
  <div class="card-listing-image" style="background-iamge:url(https://images.unsplash.com/photo-1493932484895-752d1471eab5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60); height:100px; width:100px; background-size:cover;">
  </div> -->

</div>

app/views/owners/edit.html.erb
<h3>Welcome to your user page</h3>
<p>Here's where the possibility to view and edit your profile should go </p>

app/views/owners/show.html.erb
<head>
  <title>Owner's Dashboard</title>
</head>

<div class="container-main" style="text-align:center;">
<div class="container-form-address">
  <h2>Hello Lena</h2>
   <h4>Hello, my name is Lena Kordbachech.  I love to ski, run, hike, bike!  Rent my stuff!</h4>
    <br>
    <p><%= @owner.address %></p>

  </div>
</div>


<div class="container-main">



<div class="container-main">
  <h2 class="center-text text-fat margin-title text-large">Your current listings</h2>
    <% @items.each do |item| %>
    <div class="card-horizontal">
       <%= cl_image_tag item.photos, height: 100, width: 100, crop: :fill, :class => "card-horizontal-image" %>
       <div class="card-horizontal-text">
        <p><%= link_to item.name.capitalize, item_path(item) %></p>
          <p><%= item.price %>$ </p>
          </div>
          </div>
        <% end %>


        <h2 class="center-text text-fat margin-title text-large">Your Current Deal offers</h2>
        <% @pending_deals.each do |deal| %>
        <div class="card-horizontal">
        <div class="card-horizontal-text">
        <p><%= deal.item.name %></p>
        <p><%= deal.duration %> days</p>
       <p>Total: <%= deal.duration * deal.item.price %></p>
       </div>
       </div>
        <% end %>


                <h2 class="center-text text-fat margin-title text-large">Your Current Deals</h2>
        <% @current_deals.each do |deal| %>

        <div class="card-horizontal-text">
        <p><%= deal.item.name %></p>
        <p><%= deal.duration %> days</p>
       <p>Total: <%= deal.duration * deal.item.price %></p>
       </div>
       </div>
        <% end %>
          <%= link_to 'New Item', new_item_path, class: "button-small" %>




<!--
  <div class="card-listing-image" style="background-iamge:url(https://images.unsplash.com/photo-1493932484895-752d1471eab5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60); height:100px; width:100px; background-size:cover;">
  </div> -->

</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>